### ISSUE TITLE
SetFlags must be called before Init

### ISSUE THREAD

**Issue by anee146** [MvvmCross/MvvmCross-Samples#102]
1) Clone  project from the below mentioned repository.
     https://github.com/martijn00/MvxForms
2) Update nuget packages to the latest one one
     Xamarin.Forms to 2.5.0 or above.
3) Set android project as start project.
4) Add the below mentioned line in MainActivity.cs before Xamarin.Forms.Init
     global::Xamarin.Forms.Forms.SetFlags("FastRenders_Experimental").
5) Build and run the application.

Expected behaviour.
    Application should run properly.

Actual behaviour.
    Application throws an exception says that, SetFlags must be called before Init.

A sample xamarin forms project works properly with the FastRenderer features (Not contain MvvmCross). But if applying the same in Xamarin forms with MvvmCross app fails.

Could you please help me on this?

**Comment by Cheesebaron** [comment]
Wrong place to post this issue. The sample you mention is not part of this repository. If you believe there is a bug in MvvmCross, open an issue in the MvvmCross repository.
