### ISSUE TITLE
Multi-window app support for UWP

### ISSUE THREAD

**Issue by MartinZikmund** [MvvmCross/MvvmCross-Samples#105]
Are multi-view apps in UWP supported somehow in MvvmCross?

The problem is that each app view in UWP has a separate UI dispatcher (see [documentation](https://docs.microsoft.com/en-us/windows/uwp/design/layout/show-multiple-views)), and I don't see a way to make this work with MvvmCross infrastructure easily.

Could you give me some suggestions please :-) ?

**Comment by martijn00** [comment]
The Samples repo is probably not the correct place for this question. Please open a real issue against the main repo. This would be something we can add, as WPF and Mac already have this feature: https://www.mvvmcross.com/documentation/presenters/wpf-view-presenter?scroll=625#mvxwindowpresentationattribute

**Comment by MartinZikmund** [comment]
Sorry about that, misplaced the issue
