### ISSUE TITLE
Implementing Deep linking using Xamarin Forms 3.6.0.X and MVVMCross 6.3.1

### ISSUE THREAD

**Issue by tabris84** [MvvmCross/MvvmCross-Samples#138]
Good evening, 
as described in the title I'm trying to implement the deep linking in my solution.

I didn't find anything with MVVMCross (only some example with the custom schema, but I have problems with it because the link is not visible on outlook or Gmail).

I found a good example to implement it but not in MVVMCross http://www.xamboy.com/2019/01/08/applinks-in-xamarin-forms/

In this example I need to use the Application class and in particular the method OnAppLinkRequestReceived, but I'm using MvxApplication that doesn't implement this method.

Do you have some suggestion, please?

**Comment by thewindev** [comment]
hi @tabris84 
I followed the same tutorial from xamboy and I got to this point where I have to navigate from OnAppLinkRequestReceived. Have you found a way to do it?

**Comment by saamerm** [comment]
@tabris84 & @thewindev You can implement that function yourself.
Take a look at how `OnAppLinkRequestReceived` is called using the `SendOnAppLinkRequestReceived` callback by Xamarin Forms. You can see how it's implemented in the `[FormsApplicationDelegate.cs](https://github.com/xamarin/Xamarin.Forms/blob/f35ae07a0a8471d255f7a1ebdd51499e10e0a4cb/Xamarin.Forms.Platform.iOS/FormsApplicationDelegate.cs)` and `[FormsAppCompatActivity.cs](https://github.com/xamarin/Xamarin.Forms/blob/3b7bd8e80c4a4342b83294c0384d0cc80098ae1b/Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs)`
