### ISSUE TITLE
swapi.co is dead (or temporary unavailable) 

### ISSUE THREAD

**Issue by bondarenkod** [MvvmCross/MvvmCross-Samples#141]
[swapi.co](https://swapi.co/documentation) is dead
![image](https://user-images.githubusercontent.com/3184414/79267141-50e15300-7ea1-11ea-8ad2-f20d3b4e8923.png)

needs to be replaced. 

the original (it seems like) repo is here: https://github.com/phalt/swapi 
I found some json data here: https://github.com/binxhealth/swapi

**Comment by bondarenkod** [comment]
https://jsonplaceholder.typicode.com/

**Comment by saamerm** [comment]
@bondarenkod, @martijn00 we can close this since it should be fixed now (#144)
