### ISSUE TITLE
[TipCalc Sample] Bindings not working in Forms.Droid project after updating

### ISSUE THREAD

**Issue by brud** [MvvmCross/MvvmCross-Samples#142]
I'm update xamarin and mvvmcross to actual versions (xamarin.forms are 4.6.0.726 and mvvmcross are 6.4.2), and binded values are empty - am I missing something?

**Comment by saamerm** [comment]
@brud I have updated the sample to the latest mvvmcross and xamarin forms in #143, could you please try this again with the latest code?
You can also look to see how I might have fixed your issue in the Pull request

**Comment by saamerm** [comment]
@martijn00 #143 should have fixed this as well, as per the testing. Should we close, or keep open tentatively?
