### ISSUE TITLE
TipCalc tutorial for iOS on website doesn't work

### ISSUE THREAD

**Issue by saamerm** [MvvmCross/MvvmCross-Samples#152]
When you follow the tutorial on the MVVMCross website for TipCalc, the TipView (ViewController) gives you a build error on this line:
The tutorial says to use:
            `var set = CreateBindingSet();`
but it should be
            `var set = this.CreateBindingSet<TipView, TipViewModel>();`
in order to get rid of the build error

**Comment by Cheesebaron** [comment]
CreateBindingSet(); should be fine if it is using a newer version of MvvmCross.

**Comment by saamerm** [comment]
Oops wrong repo, moved here https://github.com/MvvmCross/MvvmCross/issues/4020

**Comment by saamerm** [comment]
@Cheesebaron I guess the issue is because it's missing `this.` because that seems to be needed too?
