### ISSUE TITLE
Leanback example

### ISSUE THREAD

**Issue by OmidID** [MvvmCross/MvvmCross-Samples#154]
Hello, Someone can help with the Leanback example?

**Comment by OmidID** [comment]
@martijn00  Closed????

**Comment by martijn00** [comment]
Yes

**Comment by OmidID** [comment]
Perfect, And reason?

**Comment by martijn00** [comment]
Because you're not filling out any issue template, not asking a valid question or anything else useful

**Comment by OmidID** [comment]
The question is there. Someone can help with Leanback. Because I searched a lot for this subject on internet "CrossMvvm Leanback" and there is no example exists at all. Am I allowed to ask somebody at least?!

**Comment by martijn00** [comment]
This is not the place. Go ask on Stackoverflow
