### ISSUE TITLE
Unable to follow the TipCalc.Droid on the website

### ISSUE THREAD

**Issue by Cavan** [MvvmCross/MvvmCross-Samples#160]
Started following the TipCalc tutorials, got to the Droid one, and I'm now getting stuck with the following error using MvvmCross v 8.0.1 to setup the Application class: https://www.mvvmcross.com/documentation/tutorials/tipcalc/a-xamarinandroid-ui-project?scroll=1893#add-an-android-application-class

ERROR:
```
CS0310	'MvxAndroidSetup<App>' must be a non-abstract type with a public parameterless constructor in order to use it as parameter 'TMvxAndroidSetup' in the generic type or method 'MvxAndroidApplication<TMvxAndroidSetup, TApplication>'	TipCalc.Droid	C:\Circumference\SKILLS_DEVLOPMENT\MvvmCrossTuts\TipCalc.Core\TipCalc.Droid\MainApplication.cs	14	Active
```

**Comment by Cheesebaron** [comment]
Documentation errors should be reported in the main repository: https://github.com/MvvmCross/MvvmCross/issues/new/choose
