### ISSUE TITLE
XPlatformMenus - Unbalanced calls to begin/end appearance transitions

### ISSUE THREAD

**Issue by vecalion** [MvvmCross/MvvmCross-Samples#17]
When there are more than 1 views before MainView, the navigation to MainView causes:

```
2016-02-24 12:37:31.945 XPlatformMenusTouch[23715:1698372] Unbalanced calls to begin/end appearance transitions for <LoginView: 0x7b6eeef0>.
```

Here is a sample:
https://github.com/vecalion/MvvmCross-Samples/tree/master/XPlatformMenus

**Comment by jamsoft** [comment]
I've already solved this issue but haven't had time to overhaul he sample code and push the new version.

Set the panel hint type to PanelHintType.ResetRoot on MainView.

**Comment by vecalion** [comment]
Great, thanks!
