### ISSUE TITLE
XPlatformMenus.Android Match XPlatformMenus.iOS Functionality

### ISSUE THREAD

**Issue by benhysell** [MvvmCross/MvvmCross-Samples#26]
- iOS application has three views off of the hamburger menu, HomeView, HelpView, and SettingsView.  

- HomeView has a button that allows one to navigate to InfoView.  

- InfoView has a button to navigate to ThirdView

- ThirdView has a button to 'save and pop to home view'

Need to create similar functionality for Android

**Comment by martijn00** [comment]
Added in #36
