### ISSUE TITLE
Build issue using 4.0.0-beta7

### ISSUE THREAD

**Issue by markmadlangbayan** [MvvmCross/MvvmCross-Samples#3]
I'm getting build error.  

Resources\Values\MvxBindingAttributes.xml(2): error APT0000: Attribute "MvxItemTemplate" has already been defined

**Comment by dbeattie71** [comment]
I don't think you need MvxBindingAttributes.xml anymore.

**Comment by martijn00** [comment]
The samples need to be updated to beta-7

**Comment by markmadlangbayan** [comment]
As @dbeattie71 suggested, I removed the MvxBindingAttributes.xml file.  After that I ran into IMvxLayoutInflater can't be found and tried to find the package that contains IMvxLayoutInflaterHolder.  There maybe more issues, so I'll just hold off until this sample has been upgraded.  Looking forward to checkout out beta7.  Thanks for the quick replies.
