### ISSUE TITLE
A white screen is shown after hitting back button

### ISSUE THREAD

**Issue by vecalion** [MvvmCross/MvvmCross-Samples#4]
Here are steps:

![back](https://cloud.githubusercontent.com/assets/15178829/12017114/6506f022-ad5b-11e5-9f86-835ac94ab1a1.jpg)

Shouldn’t MvxCachingFragmentCompatActivity.OnBackPressed pass the call to the base class if BackStackEntryCount () > 1?

**Comment by jamsoft** [comment]
I'll try and get onto this tomorrow.

**Comment by vecalion** [comment]
Here is the issue:

https://github.com/MvvmCross/MvvmCross-Samples/blob/master/Samples/XPlatformMenus/XPlatformMenus.Droid/Activities/MainActivity.cs#L137

the 'forceAddToBackStack' param is always set to true and therefore the 'AddToBackstack' property of a fragment is ignored.

**Comment by martijn00** [comment]
Fixed in later updates
