### ISSUE TITLE
XPlatformMenus iOS - Broken When Attempting to Use Slideout

### ISSUE THREAD

**Issue by benhysell** [MvvmCross/MvvmCross-Samples#42]
Steps to reproduce

- Log in

- Hit hamburger menu

- Select a menu item

- Screen goes to black

I tried rolling back Mvvmcross to 4.1.1, with no luck.

One can, 'make it work' if one logs in and presses 'show info viewmodel' first, then tries to use the slide out menu.

**Comment by tofutim** [comment]
Yup, mine goes black too.

**Comment by tofutim** [comment]
When you press Settings, for example, the SettingsView ViewWillAppear gets called. Then it animates to black. It is rather mysterious why clicking Show Info ViewModel makes things better.

**Comment by tofutim** [comment]
InfoView and ThirdView use HintType.ActivePanel.

**Comment by tofutim** [comment]
from https://github.com/MvvmCross/MvvmCross-iOSSupport/blob/master/MvvmCross.iOS.Support.JASidePanels/MvxSidePanelsPresenter.cs
```
switch (panelAttribute.HintType)
                    {
                        case MvxPanelHintType.ActivePanel:
                            ChangePresentation(new MvxActivePanelPresentationHint(panelAttribute.Panel, panelAttribute.ShowPanel));
                            break;

                        case MvxPanelHintType.PopToRoot:
                            ChangePresentation(new MvxPanelPopToRootPresentationHint(panelAttribute.Panel));
                            break;

                        case MvxPanelHintType.ResetRoot:
                            ChangePresentation(new MvxPanelResetRootPresentationHint(panelAttribute.Panel));
                            break;
                    }
```

**Comment by benhysell** [comment]
I have a fix implemented in the iOS Support project, [https://github.com/MvvmCross/MvvmCross-iOSSupport/pull/29](https://github.com/MvvmCross/MvvmCross-iOSSupport/pull/29).  Since this isn't an issue with the sample I'm going to close this issue.

**Comment by tofutim** [comment]
Sweet! Thanks.
