### ISSUE TITLE
XPlatformMenus Droid

### ISSUE THREAD

**Issue by tofutim** [MvvmCross/MvvmCross-Samples#44]
When attempting to build the Droid project, I am getting the errors below. I am debugging from VS2015 to the 7" KitKat.

> Severity	Code	Description	Project	File	Line	Suppression State
> Error		No resource found that matches the given name: attr 'colorPrimary'.	XPlatformMenus.Droid	C:\MvvmCross\MvvmCross-Samples\XPlatformMenus\XPlatformMenus.Droid\Resources\values\styles.xml	5	
> Error		Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.NoActionBar'.	XPlatformMenus.Droid	C:\MvvmCross\MvvmCross-Samples\XPlatformMenus\XPlatformMenus.Droid\Resources\values\styles.xml	5	
> Error		No resource found that matches the given name: attr 'colorAccent'.	XPlatformMenus.Droid	C:\MvvmCross\MvvmCross-Samples\XPlatformMenus\XPlatformMenus.Droid\Resources\values\styles.xml	5	
> Error		No resource found that matches the given name: attr 'colorControlNormal'.	XPlatformMenus.Droid	C:\MvvmCross\MvvmCross-Samples\XPlatformMenus\XPlatformMenus.Droid\Resources\values\styles.xml	5	
> Error		No resource found that matches the given name: attr 'colorControlActivated'.	XPlatformMenus.Droid	C:\MvvmCross\MvvmCross-Samples\XPlatformMenus\XPlatformMenus.Droid\Resources\values\styles.xml	5	
> Error		No resource found that matches the given name: attr 'windowActionModeOverlay'.	XPlatformMenus.Droid	C:\MvvmCross\MvvmCross-Samples\XPlatformMenus\XPlatformMenus.Droid\Resources\values\styles.xml	5	
> Error		No resource found that matches the given name: attr 'colorControlHighlight'.	XPlatformMenus.Droid	C:\MvvmCross\MvvmCross-Samples\XPlatformMenus\XPlatformMenus.Droid\Resources\values\styles.xml	5	
> Error		No resource found that matches the given name: attr 'windowActionBar'.	XPlatformMenus.Droid	C:\MvvmCross\MvvmCross-Samples\XPlatformMenus\XPlatformMenus.Droid\Resources\values\styles.xml	5	
> Error		No resource found that matches the given name: attr 'windowNoTitle'.	XPlatformMenus.Droid	C:\MvvmCross\MvvmCross-Samples\XPlatformMenus\XPlatformMenus.Droid\Resources\values\styles.xml	5	
> Error		No resource found that matches the given name: attr 'colorPrimary'.	XPlatformMenus.Droid	C:\MvvmCross\MvvmCross-Samples\XPlatformMenus\XPlatformMenus.Droid\Resources\values\styles.xml	5	
> Error		No resource found that matches the given name: attr 'colorPrimaryDark'.	XPlatformMenus.Droid	C:\MvvmCross\MvvmCross-Samples\XPlatformMenus\XPlatformMenus.Droid\Resources\values\styles.xml	5	
>

**Comment by tofutim** [comment]
I switched machines, and this one says

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'MvxFragmentStatePagerAdapter2' could not be found (are you missing a using directive or an assembly reference?)	XPlatformMenus.Droid	C:\MvvmCross\MvvmCross-Samples\XPlatformMenus\XPlatformMenus.Droid\Fragments\Android Specific\ExampleViewPagerFragment.cs	27	Active

**Comment by Cheesebaron** [comment]
Remove the 2

**Comment by tofutim** [comment]
Are you sure? why did @benhysell  put it in?

**Comment by tofutim** [comment]
I removed the 2, will send pr when it works

**Comment by tofutim** [comment]
the Style issues at the top have to do with targeting 4.4

Compile for 4.4

Severity	Code	Description	Project	File	Line	Suppression State
Error		No resource found that matches the given name: attr 'android:statusBarColor'.	XPlatformMenus.Droid	C:\MvvmCross\MvvmCross-Samples\XPlatformMenus\XPlatformMenus.Droid\Resources\values\styles.xml	5	
Error		No resource found that matches the given name: attr 'android:elevation'.	XPlatformMenus.Droid	C:\MvvmCross\MvvmCross-Samples\XPlatformMenus\XPlatformMenus.Droid\obj\Debug\resourcecache\03233B3CA64BC4E0B6D12EDBCE1ADC9C\res\values\values.xml	132	
Error		No resource found that matches the given name: attr 'android:statusBarColor'.	XPlatformMenus.Droid	C:\MvvmCross\MvvmCross-Samples\XPlatformMenus\XPlatformMenus.Droid\Resources\values\styles.xml	5	
Error		No resource found that matches the given name: attr 'android:statusBarColor'.	XPlatformMenus.Droid	C:\MvvmCross\MvvmCross-Samples\XPlatformMenus\XPlatformMenus.Droid\Resources\values\styles.xml	5	

Compile for 5.0/6.0 okf

Of course, for a sample this is probably ok, but there are a lot of API 19 still out there, and as I mentioned earlier, by default Xamarin only installs API 19 images.

**Comment by tofutim** [comment]
what emulator are y'all using for Droid? external device?
