### ISSUE TITLE
MvvmCross 5 Tutorial

### ISSUE THREAD

**Issue by msx752** [MvvmCross/MvvmCross-Samples#62]
i wonder whether any tutorial for MvvmCross 5, i only see v4 or lower tutorial or is there a big structure changes between v4 and v5. can anybody share a up-to-date path for learning to mvvmcross?.

**Comment by flyingxu** [comment]
If you check the update date of each project, you can find some samples with MvvmCross 5. At least the StarWarsSample is using MvvmCross 5.1.1.

**Comment by msx752** [comment]
thanks it did not exist before
