### ISSUE TITLE
Unhandled exception for StarWarsSample "Trying to show a tab without a TabBarViewController

### ISSUE THREAD

**Issue by flyingxu** [MvvmCross/MvvmCross-Samples#73]
I just downloaded the StarWarsSample and run it on iOS, everything is by default, no change. But I have the following error:
>Unhandled Exception:
MvvmCross.Platform.Exceptions.MvxException: Trying to show a tab without a TabBarViewController, this is not possible!
MvvmCross.iOS.Views.Presenters.Attributes.MvxBasePresentationAttribute attribute, MvvmCross.Core.ViewModels.MvxViewModelRequest request) [0x00000] in <cc93fc0f0e404b268022d40c600485a2>:0 
  at MvvmCross.iOS.Views.Presenters.MvxIosViewPresenter.Show (MvvmCross.iOS.Views.IMvxIosView view, MvvmCross.Core.ViewModels.MvxViewModelRequest request) [0x0002c] in <cc93fc0f0e404b268022d40c600485a2>:0 
  at MvvmCros

**Comment by nmilcoff** [comment]
Thank you for filling this issue! It was already reported in [mvvmcross/2084](https://github.com/MvvmCross/MvvmCross/issues/2084). Also fixed in [this PR](https://github.com/MvvmCross/MvvmCross/pull/2085).

**Comment by flyingxu** [comment]
Thanks, I see the 5.2.0 miltstone of that PR, so we need to wait, right?

**Comment by nmilcoff** [comment]
That is right, unfortunately. If you need it working you can downgrade the MvvmCross packages to 5.1.0

**Comment by flyingxu** [comment]
Glad to know that, thanks.

**Comment by flyingxu** [comment]
I ended up using 5.2.0-unstable from https://www.myget.org/F/mvvmcross/api/v3/index.json.
I found that `SetupWindowRootNavigation` changed again recently.

**Comment by nmilcoff** [comment]
5.1.1 introduced a new logic for setting a ViewController as root. 5.2 reverts those changes and fixed the issue that makes StarWarsSample.iOS crash. Apologize for the inconvenience :(
